### ISSUE TITLE
[Maintenance] Tests don't run on platforms other than windows

### ISSUE THREAD

**Issue by ickk** [leetvr/hotham#240] opened 2022-07-06 01:25 UTC
## Description
We set `#[cfg(target_os = "windows")]` for some tests, such as https://github.com/leetvr/hotham/blob/64f022677f1ba699387ebb2947ebe9f3ba35873a/hotham/src/asset_importer/mod.rs#L338
in order to prevent these tests from running in CI, since they won't at the moment.

This means tests won't run on other OSes such as linux.

## To do
- [ ] Implement a workaround

or 
- [ ] Get a CI runner that will work for us, and remove the cfg attribute

**Comment by kanerogers** [comment] 2022-10-06 01:33
Duplicate of #164

**Closed by kanerogers** 2022-10-06 01:33 UTC
Labels: maintenance
